packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@microsoft/api-extractor': ^7.52.1
  '@semantic-release/changelog': ^6.0.3
  '@semantic-release/git': ^10.0.1
  '@semantic-release/npm': ^12.0.1
  '@types/minimist': ^1.2.5
  '@types/node': ^22.13.13
  '@typescript-eslint/eslint-plugin': ^8.28.0
  '@typescript-eslint/parser': ^8.28.0
  esbuild: ^0.25.1
  esbuild-plugin-wasm-pack: ^1.1.0
  eslint: ^9.23.0
  lint-staged: ^15.5.0
  magic-string: ^0.30.17
  minimist: ^1.2.8
  semantic-release: ^24.2.3
  simple-git-hooks: ^2.12.1
  ts-node: ^10.9.2
  typescript: ^5.8.2
  vite: ^6.2.3
  wasm-opt: ^1.4.0
onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - simple-git-hooks
  - wasm-opt
version: '>=10'
