#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$DIR")"

HIGHWAY="${ROOT_DIR}/highway"

if ! command -v wasm-pack >/dev/null 2>&1; then
  echo "wasm-pack is not installed"
  exit 1
fi

function build() {
  local out_name="$1"
  local out_dir="$2"
  wasm-pack build "$HIGHWAY" \
    --out-name "$out_name" \
    --target web \
    --out-dir "$out_dir" \
    --release
#    --no-typescript \
}

function main() {
  build "highwayhash" "${ROOT_DIR}/js/highwayhash-wasm/lib/highwayhash"
  RUSTFLAGS="-C target-feature=+simd128" build "highwayhash-simd" "${ROOT_DIR}/js/highwayhash-wasm/lib/highwayhash-simd"
}

main "$@"
