#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$(dirname "$DIR")"

HIGHWAY_WASM="${ROOT_DIR}/js/highway-wasm/lib/highway/highway_bg.wasm"
HIGHWAY_SIMD_WASM="${ROOT_DIR}/js/highway-wasm/lib/highway-simd/highway-simd_bg.wasm"

#if ! command -v wasm-opt >/dev/null 2>&1; then
#  echo "wasm-opt is not installed"
#  exit 1
#fi

# read current file size
function get_file_size() {
  wc -c < "$1"
}

function optimize_size() {
  local input_size
  local output_size
  input_size=$(get_file_size "$1")
  node_modules/.bin/wasm-opt -Os "$1" -o "${ROOT_DIR}/opt.wasm"
  mv "${ROOT_DIR}/opt.wasm" "$1"
  output_size=$(get_file_size "$1")
  echo "Optimized $1 from $input_size to $output_size"
}

function main() {
  optimize_size "$HIGHWAY_WASM"
  optimize_size "$HIGHWAY_SIMD_WASM"
}

main "$@"
