name: ci

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm build

      - if: github.event_name == 'push'
        run: tar cf - ./dist | gzip --best > dist.tar.gz

      - if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist.tar.gz
